# Generated by Django 5.2.7 on 2025-11-14 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamatajwells', '0001_initial'),
        ('market', '0009_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellery',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'jwells'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.category'),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.subcategory'),
        ),
    ]
