# Generated by Django 5.2.7 on 2025-11-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('market', 'Market'), ('jwells', 'Mamata Jewells')], max_length=20)),
            ],
        ),
    ]
