# Generated by Django 5.2.7 on 2025-11-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_vendor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
